site_name: TianKaiM's Blog

site_description: Personal Blog.
site_author: TianKaiM
site_url: https://tiankaima.github.io/docs

# Copyright
copyright: TianKaiM, MIT License

theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    primary: indigo
    accent: indigo
  features:
    - instant
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true